### ISSUE TITLE
Testing framework needed

### ISSUE THREAD

**Issue by dbaelde** [E-Sh4rk/tim-dodge#1]
It is good to have some first tests in `tim_tests/Program.cs` (abeccd046b9f3dccd6022fef2c49ed7d5e65a597) but these are not usable unit tests. You need a proper unit testing framework which should help you to write tests as independent units, organize them in collections, and selectively run tests (perhaps just one test, or just one collection).

**Comment by E-Sh4rk** [comment]
We are now using NUnit to perform unit tests.
